export const RECORD_ATTENDANCE_LOAD = "RECORD_ATTENDANCE_LOAD";
export const RECORD_ATTENDANCE_SUCCESS = "RECORD_ATTENDANCE_SUCCESS";
export const LOAD_ATTENDANCE_START = "LOAD_ATTENDANCE_START";
export const LOAD_ATTENDANCE_SUCCESS = "LOAD_ATTENDANCE_SUCCESS";